name: Terraform Lint
author: Christian Shaw<chris@koda.software>
description: Lint a Terraform project

inputs:
  continue-on-error:
    type: boolean
    required: false
    default: false

  setup:
    type: boolean
    required: false
    default: true

  minimum-severity-level:
    type: choice
    options:
      - error
      - warning
      - notice
    default: warning

  tflint-version:
    type: string
    required: false
    default: v0.48.0

  working-directory:
    type: string
    required: false
    default: terraform

outputs:
  stdout:
    value: ${{ steps.tflint.outputs.stdout }}

runs:
  using: composite
  steps:
    - name: "Setup: TFLint"
      if: ${{ inputs.setup }}
      uses: terraform-linters/setup-tflint@v3
      with:
        tflint_wrapper: true
        tflint_version: ${{ inputs.tflint-version }}

    - name: "TF: Lint Init"
      run: tflint --init
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - id: tflint
      name: "TF: Lint"
      run: tflint --recursive --no-color --minimum-failure-severity ${{ inputs.minimum-severity-level }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: ${{ inputs.continue-on-error }}
