name: Terragrunt Apply
author: Christian Shaw<chris@koda.software>
description: Applies a Terragrunt plan for a project

inputs:
  google-credentials:
    default: ''
    required: false
    type: string

  working-directory:
    required: true
    type: string

outputs:
  stdout:
    value: ${{ steps.apply.outputs.stdout }}

runs:
  using: composite
  steps:
    - id: apply
      name: "TG: Apply"
      run: |
        {
          echo 'stdout<<EOF'
          terragrunt apply -no-color -auto-approve
          echo EOF
        } >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GOOGLE_CREDENTIALS: ${{ inputs.google-credentials }}
