
name: Setup ASDF with caching
author: Christian Shaw<chris@koda.software>
description: Sets up ASDF and installs tools utilising caching to optimise performance

inputs:
  asdf-cache-directory:
    required: true
    type: string

  os:
    required: true
    type: string

  terraform-lockfile-path:
    default: ''
    required: false
    type: string

  terraform-plugin-cache-directory:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Create Plugin Cache Dir
      shell: bash
      run: |
        mkdir -p $TF_PLUGIN_CACHE_DIR
        mkdir -p $ASDF_DIR
      env:
        TF_PLUGIN_CACHE_DIR: ${{ inputs.terraform-plugin-cache-directory }}
        ASDF_DIR: ${{ inputs.asdf-cache-directory }}

    - name: Terraform Plugin Cache
      uses: actions/cache@v4.0.1
      with:
        path: ${{ env.TF_PLUGIN_CACHE_DIR }}
        key: ${{ inputs.os }}-terraform-plugin-cache-${{ hashFiles('**${{ inputs.terraform-lock-file-path }}/.terraform.lock.hcl') }}
      env:
        TF_PLUGIN_CACHE_DIR: ${{ inputs.terraform-plugin-cache-directory }}

    - uses: asdf-vm/actions/setup@v3

    - name: ASDF Plugin Cache
      uses: actions/cache@v4.0.1
      with:
        path: ${{ env.ASDF_DIR }}
        key: ${{ inputs.os }}-asdf-plugin-cache-${{ hashFiles('**/.tool-versions') }}
      env:
        ASDF_DIR: ${{ inputs.asdf-cache-directory }}

    - uses: asdf-vm/actions/install@v3
