name: Terragrunt Plan
author: Christian Shaw<chris@koda.software>
description: Runs Terragrunt plan on a project

inputs:
  google-credentials:
    default: ''
    required: false
    type: string

  working-directory:
    required: true
    type: string

outputs:
  stdout:
    value: ${{ steps.plan.outputs.stdout }}

runs:
  using: composite
  steps:
    - id: plan
      name: "TG: Plan"
      run: |
        {
          echo 'stdout<<EOF'
          terragrunt plan -no-color
          echo EOF
        } >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GOOGLE_CREDENTIALS: ${{ inputs.google-credentials }}
