name: Comment to a PR
author: Christian Shaw
description: Adds a comment to a PR

inputs:
  body:
    type: string
    required: true

  github-token:
    type: string
    required: true

runs:
  using: composite
  steps:
    - uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ${{ inputs.body }}
          })