name: Terraform Format
author: Christian Shaw<christian.shaw@nokkel.com>
description: Check the format of a Terraform project

inputs:
  continue-on-error:
    type: boolean
    required: false
    default: true

  setup:
    type: boolean
    required: false
    default: false

  terraform-version:
    type: string
    required: false
    default: "1.1.7"

  working-directory:
    type: string
    required: false
    default: ./terraform

outputs:
  stdout:
    value: ${{ steps.fmt.outputs.TF_FMT_OUTPUT }}

runs:
  using: composite
  steps:
    - id: setup
      name: "TF: Setup"
      if: ${{ inputs.setup }}
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - id: fmt
      name: "TF: Format"
      run: echo "TF_FMT_OUTPUT=$(terraform fmt -check -no-color)" >> GITHUB_OUTPUT
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: ${{ inputs.continue-on-error }}
